name: Daily MBTiles Upload

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y tippecanoe

      - name: Install Python deps
        run: |
          pip install -r requirements.txt

      - name: Run script
        env:
          MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
          MAPBOX_TILESET_ID: ${{ secrets.MAPBOX_TILESET_ID }}
        run: |
          python run.py
