name: Construir y publicar PMTiles diario

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  construir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias del sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libsqlite3-dev zlib1g-dev golang-go

      - name: Compilar e instalar tippecanoe
        run: |
          git clone --depth=1 https://github.com/mapbox/tippecanoe.git
          cd tippecanoe
          make -j"$(nproc)"
          sudo make install

      - name: Instalar pmtiles CLI
        run: |
          GOBIN=$HOME/go/bin go install github.com/protomaps/pmtiles/cmd/pmtiles@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Instalar dependencias de Python
        run: |
          pip install -r requirements.txt

      - name: Ejecutar pipeline
        run: |
          python run.py

      - name: Convertir a PMTiles y preparar sitio
        run: |
          mkdir -p public
          pmtiles convert data/estaciones.mbtiles public/estaciones.pmtiles
          cp data/stats.json public/stats.json
          printf '<!doctype html><meta charset="utf-8"><h1>PMTiles publicado</h1>' > public/index.html

      - name: Subir artefacto
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  desplegar:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: construir
    steps:
      - name: Desplegar
        id: deployment
        uses: actions/deploy-pages@v4
