name: Build and Publish PMTiles Daily

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libsqlite3-dev zlib1g-dev

      - name: Build and install tippecanoe
        run: |
          git clone --depth=1 https://github.com/mapbox/tippecanoe.git
          cd tippecanoe
          make -j"$(nproc)"
          sudo make install

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pipeline
        run: |
          python run.py

      - name: Convert to PMTiles and prepare site
        run: |
          mkdir -p public
          docker run --rm -v "${{ github.workspace }}:/work" -w /work protomaps/go-pmtiles:latest pmtiles convert data/estaciones.mbtiles public/estaciones.pmtiles
          cp data/stats.json public/stats.json
          printf '<!doctype html><meta charset="utf-8"><h1>PMTiles published</h1>' > public/index.html

      - name: Upload artifact to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
