name: Build and Publish PMTiles Daily

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y tippecanoe curl

      - name: Install PMTiles CLI
        run: |
          PMTILES_VERSION="v1.28.1"
          curl -L -o pmtiles "https://github.com/protomaps/go-pmtiles/releases/download/${PMTILES_VERSION}/pmtiles-linux-amd64"
          chmod +x pmtiles
          sudo mv pmtiles /usr/local/bin/pmtiles
          pmtiles --help

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pipeline
        run: |
          python run.py

      - name: Convert to PMTiles and prepare site
        run: |
          mkdir -p public
          pmtiles convert data/estaciones.mbtiles public/estaciones.pmtiles
          cp data/stats.json public/stats.json
          printf '<!doctype html><meta charset="utf-8"><h1>PMTiles published</h1>' > public/index.html

      - name: Upload artifact to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
